version: 0.2

env:
  variables:
    EC2_USER: ec2-user
    EC2_HOST: 18.231.178.29
    APP_DIR: /home/ec2-user/app
    AMBIENTE: dev
    API_KEY: gQV5g<1A<6c7
    DEV_USER_NAME: root
    DEV_PASSWORD: root
    DB_URL_NODE: database_url
    DB_POOL_TIMEOUT: 120
    DB_POOL_MAX: 10
    DB_POOL_MIN: 1
  secrets-manager:
    EC2_KEY_PEM: my-ec2-key:SecretString.pem  # Recupera a chave privada do Secrets Manager

phases:
  install:
    commands:
      - echo "🔑 Salvando chave privada temporariamente..."
      - echo "$EC2_KEY_PEM" > /tmp/key.pem
      - chmod 400 /tmp/key.pem
      - echo "🟢 Instalando dependências..."
      - npm install

  build:
    commands:
      - echo "⚙️ Compilando TypeScript..."
      - npm run build

  post_build:
    commands:
      - echo "📦 Preparando artefatos..."
      - mkdir -p dist-artifacts
      - cp -r dist/* dist-artifacts/
      - echo "🚀 Copiando build para o EC2..."
      - scp -o StrictHostKeyChecking=no -i /tmp/key.pem -r dist-artifacts/* $EC2_USER@$EC2_HOST:$APP_DIR
      - echo "🔥 Iniciando aplicação NestJS na EC2..."
      - ssh -o StrictHostKeyChecking=no -i /tmp/key.pem $EC2_USER@$EC2_HOST "mkdir -p $APP_DIR && cd $APP_DIR && nohup node dist/main.js > nestjs.log 2>&1 &"

artifacts:
  files:
    - '**/*'
